repos:

############
### RUFF ###
############

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.0
  hooks:
    - id: ruff-check
    - id: ruff-format

############
### MYPY ###
############

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.16.1'
    hooks:
    -   id: mypy
        args: [--check-untyped-defs]
        additional_dependencies: [
          "types-docutils",
          "sphinx",
          "types-xmltodict>=0.14.0.20241009",
          "pydantic>=2.11.7",
          "pytest-cov",
          "pydantic-settings>=2.10.1",
        ]
