[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

########################
### PROJECT METADATA ###
########################

[project]
name = "kaestchen"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = []
authors = [
    {name = "maromei", email = "maromei@proton.me"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "lxml>=6.0.0",
    "pydantic>=2.11.7",
    "xmltodict>=0.14.2",
]

[project.urls]
Documentation = "https://github.com/maromei/kaestchen#readme"
Issues = "https://github.com/maromei/kaestchen/issues"
Source = "https://github.com/maromei/kaestchen"

[tool.hatch.version]
path = "src/kaestchen/__about__.py"

###################
### TOOL PYTEST ###
###################

[tool.pytest.ini_options]
testpaths = ["src/tests"]

#################
### TOOL MYPY ###
#################

[tool.mypy]
plugins = []

[dependency-groups]
dev = [
    "docutils>=0.21.2",
    "pytest-cov>=6.2.1",
    "sphinx>=8.1.3",
]

####################
### ENVIRONMENTS ###
####################

### Default ###

[tool.hatch.envs.default]
installer = "uv"
extra-dependencies = [
    "ipython"
]

### Style ###

[tool.hatch.envs.style]
installer = "uv"
extra-dependencies = [
    "ruff",
    "mypy",
    "pre-commit",
    "types-docutils",
    "sphinx",
    "types-xmltodict>=0.14.0.20241009",
    "pytest-cov"
]

[tool.hatch.envs.style.scripts]
pre-commit-install = "pre-commit install" # install pre-commit hooks
pre-commit-update = "pre-commit autoupdate" # update hook versions
pre-commit-test = "pre-commit run --all-files"
check = [
    "ruff check src",
    "mypy src --check-untyped-defs"
]

### Docs ###

[tool.hatch.envs.docs]
installer = "uv"
extra-dependencies = [
    "sphinx==8.2.3",
    "sphinx-autobuild==2024.10.3",
    "myst-parser==4.0.1",
    "sphinx_rtd-theme",
]

[tool.hatch.envs.docs.scripts]
serve = "sphinx-autobuild docs/source docs/build/html"

### Tests ###

[tool.hatch.envs.tests]
installer = "uv"
extra-dependencies = [
    "pytest-cov==6.1.1"
]

[tool.hatch.envs.tests.scripts]
all = "pytest {args}"
module = "pytest src/tests/{args}"
cov = [
    "pytest --cov=kaestchen --cov-report html",
    "firefox file://$PWD/htmlcov/index.html"
]
